#! /usr/bin/env ruby
require 'pg'

def main(args)
  if args.size.zero?
    puts help_message
    exit(0)
  end

  db = PG.connect(dbname: 'cli_app')

  case args[0]
  when 'list'
    display_list(db)
  when 'add'
    process_add(db, args)
  end

end

def display_list(db)
  result = db.exec('select id, amount, memo, date(created_on) as date from expenses')
  result.each do |tuple|
    id =     tuple['id']
    amount = tuple['amount']
    memo =   tuple['memo']
    date =   tuple['date']

    puts "#{id.rjust(5)} | #{date} | #{amount.rjust(10)} | #{memo}"
  end
end

def process_add(db, args)
  if args.size < 3
    puts 'You must provide an amount and memo'
    return
  end

  amount = args[1]
  memo = args[2]

  sql = <<~SQL
    INSERT INTO expenses(amount, memo)
      VALUES
        (#{amount}, '#{memo}');
  SQL
  db.exec(sql)
end

def help_message
  <<~MESSAGE
    An expense recording system

    Commands:

    add AMOUNT MEMO [DATE] - record a new expense
    clear - delete all expenses
    list - list all expenses
    delete NUMBER - remove expense with id NUMBER
    search QUERY - list expenses with a matching memo field
  MESSAGE
end

main(ARGV)
